# Generated by Django 3.2.7 on 2021-09-19 11:17

import api_project.models
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0002_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_url', models.CharField(max_length=32, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=api_project.models.nameFile),
        ),
    ]
