# Generated by Django 3.2.7 on 2021-09-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0003_auto_20210919_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryurl',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api_project.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temporaryurl',
            name='temp_url',
            field=models.CharField(max_length=32),
        ),
    ]
