# Generated by Django 3.2.7 on 2021-09-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0005_temporaryurl_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryUrl',
        ),
    ]
