# Generated by Django 3.2.7 on 2021-09-19 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_project', '0006_delete_temporaryurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_url', models.CharField(max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_project.image')),
            ],
        ),
    ]
