# Generated by Django 3.2.7 on 2021-09-19 12:54

import api_project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0007_temporaryurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryurl',
            name='image',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='temporaryurl',
            name='temp_url',
            field=models.CharField(default=api_project.models.TemporaryUrl.create_url, max_length=100),
        ),
    ]
