# Generated by Django 3.2.7 on 2021-09-19 15:31

import api_project.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_project', '0007_temporaryurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to=api_project.models.nameFile, verbose_name='Original image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Image title'),
        ),
        migrations.AlterField(
            model_name='temporaryurl',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='temporaryurl',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='temporaryurl',
            name='expires',
            field=models.IntegerField(verbose_name='Seconds to expire'),
        ),
        migrations.AlterField(
            model_name='temporaryurl',
            name='image',
            field=models.IntegerField(verbose_name='Image ID'),
        ),
        migrations.AlterField(
            model_name='temporaryurl',
            name='temp_url',
            field=models.URLField(max_length=100, null=True, verbose_name='Temporary Link'),
        ),
    ]
