# Generated by Django 3.2.7 on 2021-09-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0008_auto_20210919_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryurl',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_project.image', verbose_name='Image ID'),
        ),
    ]
