# Generated by Django 3.2.7 on 2021-09-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0009_alter_temporaryurl_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaryurl',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='temporaryurl',
            old_name='image',
            new_name='image_id',
        ),
    ]
