# Generated by Django 3.2.7 on 2021-09-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0010_auto_20210919_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaryurl',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='temporaryurl',
            old_name='image_id',
            new_name='image',
        ),
    ]
