# Generated by Django 3.2.7 on 2021-09-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_project', '0012_auto_20210919_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryurl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
